# Generated by Django 2.2.1 on 2019-05-29 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfmodel', '0002_auto_20190529_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='fhmodel',
            name='AllocationPlan',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fhmodel',
            name='CQCXR',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fhmodel',
            name='GQDJR',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fhmodel',
            name='GXL',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fhmodel',
            name='MarketType',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fhmodel',
            name='NOTICEDATE',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fhmodel',
            name='ProjectProgress',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fhmodel',
            name='ReportingPeriod',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fhmodel',
            name='ResultsbyDate',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fhmodel',
            name='SGBL',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fhmodel',
            name='SZZBL',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fhmodel',
            name='XJFH',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fhmodel',
            name='YAGGR',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fhmodel',
            name='ZGBL',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='fhmodel',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='fhmodel',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
